# Generated by Django 4.1.3 on 2023-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_phone_numbber_useraccount_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='cuntry_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
