# Generated by Django 4.1.3 on 2023-07-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraccount_cuntry_name_alter_useraccount_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='cuntry_name',
            new_name='country_name',
        ),
    ]
