# Generated by Django 4.1.3 on 2023-07-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_cuntry_name_useraccount_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='picture_id',
        ),
    ]
