# Generated by Django 4.1.3 on 2023-07-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appjiviefy', '0007_alter_podcast_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
